### ISSUE TITLE
npm start 失败

### ISSUE THREAD

**Issue by Carrie999** [frontend9/fe9-market#3]
> react-app-rewired start  internal/modules/cjs/loader.js:583  
   throw err;    
 ^  Error: Cannot find module '/Users/orion/Desktop/fe9-market-master/node_modules/react-scripts/config/webpack.config.dev'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/orion/Desktop/fe9-market-master/node_modules/react-app-rewired/scripts/start.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fe9-market@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fe9-market@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by fkysly** [comment]
有 npm install 么

**Comment by Carrie999** [comment]
@fkysly 安装了，是react-app-rewire-less出了问题

**Comment by Carrie999** [comment]
解决了。。。很诡异的解决了，忽略报错运行就没问题
